bundler_args: --without development --path=~/.bundle
language: ruby
rvm:
- 2.0.0
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script: bundle exec middleman build
after_script:
after_success:
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
    - 'http://ngs-hubot.herokuapp.com/travisci/hooks'

